#define SERVO_I2C_ADDRESS 23

#define SERVO_I2C_SEND_TARGET 'T'
#define SERVO_I2C_SEND_MIN_ANGLE 'S'
#define SERVO_I2C_SEND_MAX_ANGLE 'B'
#define SERVO_I2C_SEND_MAX_SPEED 'V'
#define SERVO_I2C_SEND_ACCELERATION 'A'
#define SERVO_I2C_SEND_MAX_POWER 'P'
#define SERVO_I2C_SEND_PID_KP 'p'
#define SERVO_I2C_SEND_PID_KI 'i'
#define SERVO_I2C_SEND_PID_KD 'd'


#define SERVO_I2C_READ_ANGLE 'R'
